# render.yaml
services:
  - type: web
    name: gestor-contratos
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port=$PORT --server.enableCORS=false"
